# See the documentation for more information:
# https://packit.dev/docs/configuration/
upstream_tag_template: v{version}

# add or remove files that should be synced
files_to_sync:
    - rust-coreos-installer.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: coreos-installer

packages:
  coreos-installer-fedora:
    specfile_path: rust-coreos-installer.spec
    downstream_package_name: rust-coreos-installer
    actions:
      post-upstream-clone:
        - wget https://src.fedoraproject.org/rpms/rust-coreos-installer/raw/rawhide/f/rust-coreos-installer.spec
      changelog-entry:
        - bash -c 'echo "- New upstream release"'

jobs: 

- job: propose_downstream
  trigger: release
  packages: [coreos-installer-fedora]
  dist_git_branches:
    - fedora-rawhide

- job: koji_build
  trigger: commit
  packages: [coreos-installer-fedora]
  dist_git_branches:
    - fedora-all

- job: bodhi_update
  trigger: commit
  packages: [coreos-installer-fedora]
  dist_git_branches:
    - fedora-all
